import { Book } from "@/types/type";

const books: Book[] = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Fiction",
    price: 10.99,
    language: "English",
    yearPublished: 1925,
    rating: 4.5,
    stockQuantity: 8,
    coverImageUrl: "/example.webp",
    description:
      "A classic novel that explores themes of wealth, love, and the American Dream in the Jazz Age.",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    genre: "Sci-Fi",
    price: 12.49,
    language: "English",
    yearPublished: 1949,
    rating: 4.7,
    stockQuantity: 15,
    coverImageUrl: "/example.webp",
    description:
      "A dystopian novel about a totalitarian regime that uses surveillance and propaganda to control society.",
  },
  {
    id: 3,
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    genre: "Fiction",
    price: 14.99,
    language: "Spanish",
    yearPublished: 1967,
    rating: 4.6,
    stockQuantity: 10,
    coverImageUrl: "/example.webp",
    description:
      "A multigenerational story of the Buendía family, blending magical realism with the history of Colombia.",
  },
  {
    id: 4,
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Fiction",
    price: 9.99,
    language: "English",
    yearPublished: 1988,
    rating: 4.2,
    stockQuantity: 20,
    coverImageUrl: "/example.webp",
    description:
      "A philosophical tale about a shepherd named Santiago and his quest to find a hidden treasure.",
  },
  {
    id: 5,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genre: "Mystery",
    price: 16.99,
    language: "English",
    yearPublished: 2019,
    rating: 4.3,
    stockQuantity: 12,
    coverImageUrl: "/example.webp",
    description:
      "A psychological thriller about a woman who stops speaking after a shocking act of violence.",
  },
  {
    id: 6,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    genre: "Non-Fiction",
    price: 18.99,
    language: "English",
    yearPublished: 2011,
    rating: 4.8,
    stockQuantity: 5,
    coverImageUrl: "/example.webp",
    description:
      "An exploration of the history of humankind, from the Stone Age to the present, and how we came to dominate the planet.",
  },
  {
    id: 7,
    title: "Becoming Michelle",
    author: "Michelle Obama",
    genre: "Biography",
    price: 16.99,
    language: "English",
    yearPublished: 2018,
    rating: 4.9,
    stockQuantity: 10,
    coverImageUrl: "/example.webp",
    description:
      "A memoir by the former First Lady, chronicling her journey through life, love, and leadership.",
  },
  {
    id: 8,
    title: "The Subtle Art of Focus",
    author: "Mark Manson",
    genre: "Self-Help",
    price: 14.99,
    language: "English",
    yearPublished: 2016,
    rating: 4.5,
    stockQuantity: 12,
    coverImageUrl: "/example.webp",
    description:
      "A counterintuitive approach to living a good life, focusing on values and priorities.",
  },
  {
    id: 9,
    title: "Atomic Habits for Growth",
    author: "James Clear",
    genre: "Self-Help",
    price: 17.99,
    language: "English",
    yearPublished: 2018,
    rating: 4.8,
    stockQuantity: 8,
    coverImageUrl: "/example.webp",
    description:
      "A guide to building good habits and breaking bad ones, with actionable strategies for improvement.",
  },
  {
    id: 10,
    title: "Educated: A Memoir",
    author: "Tara Westover",
    genre: "Memoir",
    price: 15.49,
    language: "English",
    yearPublished: 2018,
    rating: 4.7,
    stockQuantity: 6,
    coverImageUrl: "/example.webp",
    description:
      "A powerful memoir about growing up in a strict and abusive household in rural Idaho and pursuing education.",
  },
  {
    id: 11,
    title: "Dune: The Sand Legacy",
    author: "Frank Herbert",
    genre: "Sci-Fi",
    price: 13.99,
    language: "English",
    yearPublished: 1965,
    rating: 4.6,
    stockQuantity: 15,
    coverImageUrl: "/example.webp",
    description:
      "A science fiction epic about a desert planet and the battle for control over its vital resource, spice.",
  },
  {
    id: 12,
    title: "Pride and Love",
    author: "Jane Austen",
    genre: "Fiction",
    price: 9.99,
    language: "English",
    yearPublished: 1813,
    rating: 4.8,
    stockQuantity: 18,
    coverImageUrl: "/example.webp",
    description:
      "A romantic novel exploring the manners and matrimonial machinations of British Regency society.",
  },
  {
    id: 13,
    title: "The Catcher in Shadows",
    author: "J.D. Salinger",
    genre: "Fiction",
    price: 10.99,
    language: "English",
    yearPublished: 1951,
    rating: 4.2,
    stockQuantity: 20,
    coverImageUrl: "/example.webp",
    description:
      "The story of Holden Caulfield, a teenager navigating the challenges of growing up in mid-20th century America.",
  },
  {
    id: 14,
    title: "The Endless Road",
    author: "Cormac McCarthy",
    genre: "Post-Apocalyptic",
    price: 12.99,
    language: "English",
    yearPublished: 2006,
    rating: 4.4,
    stockQuantity: 9,
    coverImageUrl: "/example.webp",
    description:
      "A haunting novel about a father and son journeying through a bleak, post-apocalyptic world.",
  },
  {
    id: 15,
    title: "The Tale of the Handmaid",
    author: "Margaret Atwood",
    genre: "Dystopian",
    price: 14.49,
    language: "English",
    yearPublished: 1985,
    rating: 4.6,
    stockQuantity: 12,
    coverImageUrl: "/example.webp",
    description:
      "A chilling vision of a totalitarian regime that subjugates women, told through the eyes of a handmaid.",
  },
  {
    id: 16,
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    genre: "Fantasy",
    price: 15.99,
    language: "English",
    yearPublished: 1950,
    rating: 4.7,
    stockQuantity: 20,
    coverImageUrl: "/example.webp",
    description:
      "A series of fantasy tales centered around the magical world of Narnia and its inhabitants.",
  },
  {
    id: 17,
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    genre: "Science",
    price: 18.49,
    language: "English",
    yearPublished: 1988,
    rating: 4.8,
    stockQuantity: 15,
    coverImageUrl: "/example.webp",
    description:
      "A landmark work exploring cosmology, black holes, and the nature of the universe.",
  },
  {
    id: 18,
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    genre: "Mystery",
    price: 14.99,
    language: "English",
    yearPublished: 2005,
    rating: 4.6,
    stockQuantity: 12,
    coverImageUrl: "/example.webp",
    description:
      "A thrilling mystery about a journalist and a hacker uncovering dark secrets in Sweden.",
  },
  {
    id: 19,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: "Dystopian",
    price: 12.99,
    language: "English",
    yearPublished: 2008,
    rating: 4.8,
    stockQuantity: 25,
    coverImageUrl: "/example.webp",
    description:
      "A gripping dystopian tale of survival and rebellion set in the nation of Panem.",
  },
  {
    id: 20,
    title: "Life of Pi",
    author: "Yann Martel",
    genre: "Fiction",
    price: 13.49,
    language: "English",
    yearPublished: 2001,
    rating: 4.7,
    stockQuantity: 18,
    coverImageUrl: "/example.webp",
    description:
      "A captivating story of a boy stranded at sea with a Bengal tiger named Richard Parker.",
  },
  {
    id: 21,
    title: "The Shining",
    author: "Stephen King",
    genre: "Horror",
    price: 14.99,
    language: "English",
    yearPublished: 1977,
    rating: 4.6,
    stockQuantity: 10,
    coverImageUrl: "/example.webp",
    description:
      "A horror classic about a haunted hotel and the unraveling mind of its caretaker.",
  },
  {
    id: 22,
    title: "The Goldfinch",
    author: "Donna Tartt",
    genre: "Fiction",
    price: 16.99,
    language: "English",
    yearPublished: 2013,
    rating: 4.5,
    stockQuantity: 8,
    coverImageUrl: "/example.webp",
    description:
      "A Pulitzer Prize-winning novel about art, loss, and survival after a tragedy.",
  },
  {
    id: 23,
    title: "The Giver",
    author: "Lois Lowry",
    genre: "Dystopian",
    price: 10.99,
    language: "English",
    yearPublished: 1993,
    rating: 4.4,
    stockQuantity: 14,
    coverImageUrl: "/example.webp",
    description:
      "A thought-provoking novel set in a seemingly utopian society with a hidden dark side.",
  },
  {
    id: 24,
    title: "The Pillars of the Earth",
    author: "Ken Follett",
    genre: "Historical Fiction",
    price: 17.49,
    language: "English",
    yearPublished: 1989,
    rating: 4.7,
    stockQuantity: 11,
    coverImageUrl: "/example.webp",
    description:
      "An epic tale about the construction of a cathedral in medieval England.",
  },
  {
    id: 25,
    title: "Inferno's Labyrinth",
    author: "Dan Brown",
    genre: "Thriller",
    price: 14.99,
    language: "English",
    yearPublished: 2013,
    rating: 4.5,
    stockQuantity: 10,
    coverImageUrl: "/example.webp",
    description:
      "A gripping tale that delves into Dante's Inferno, with mysteries and art intertwining.",
  },
  {
    id: 26,
    title: "A Man Called Ove",
    author: "Fredrik Backman",
    genre: "Fiction",
    price: 13.49,
    language: "English",
    yearPublished: 2012,
    rating: 4.8,
    stockQuantity: 12,
    coverImageUrl: "/example.webp",
    description:
      "A heartwarming story about a grumpy old man and the community that changes his life.",
  },
  {
    id: 27,
    title: "Brave New Future",
    author: "Aldous Huxley",
    genre: "Sci-Fi",
    price: 11.99,
    language: "English",
    yearPublished: 1932,
    rating: 4.7,
    stockQuantity: 9,
    coverImageUrl: "/example.webp",
    description:
      "A dystopian novel exploring the effects of technology and consumerism on society.",
  },
  {
    id: 28,
    title: "The Road to Middle-earth",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    price: 19.99,
    language: "English",
    yearPublished: 1954,
    rating: 4.9,
    stockQuantity: 15,
    coverImageUrl: "/example.webp",
    description:
      "An epic journey of courage, friendship, and the battle against darkness in Middle-earth.",
  },
  {
    id: 29,
    title: "Circe's Song",
    author: "Madeline Miller",
    genre: "Fantasy",
    price: 14.99,
    language: "English",
    yearPublished: 2018,
    rating: 4.6,
    stockQuantity: 8,
    coverImageUrl: "/example.webp",
    description:
      "A powerful retelling of the story of Circe, the witch of Aiaia from Greek mythology.",
  },
  {
    id: 30,
    title: "The Midnight Library",
    author: "Matt Haig",
    genre: "Fantasy",
    price: 12.99,
    language: "English",
    yearPublished: 2020,
    rating: 4.7,
    stockQuantity: 14,
    coverImageUrl: "/example.webp",
    description:
      "A magical library offering second chances and the possibility to live different lives.",
  },
  {
    id: 31,
    title: "The Testaments",
    author: "Margaret Atwood",
    genre: "Dystopian",
    price: 16.49,
    language: "English",
    yearPublished: 2019,
    rating: 4.8,
    stockQuantity: 7,
    coverImageUrl: "/example.webp",
    description:
      "A sequel to 'The Handmaid's Tale,' exploring the fate of Gilead through multiple voices.",
  },
  {
    id: 32,
    title: "The Water Dancer",
    author: "Ta-Nehisi Coates",
    genre: "Historical Fiction",
    price: 15.99,
    language: "English",
    yearPublished: 2019,
    rating: 4.4,
    stockQuantity: 12,
    coverImageUrl: "/example.webp",
    description:
      "A gripping tale of slavery, memory, and freedom through a young man's magical journey.",
  },
  {
    id: 33,
    title: "Little Fires Everywhere",
    author: "Celeste Ng",
    genre: "Fiction",
    price: 14.49,
    language: "English",
    yearPublished: 2017,
    rating: 4.6,
    stockQuantity: 10,
    coverImageUrl: "/example.webp",
    description:
      "A thought-provoking novel about class, privilege, and the secrets of suburban life.",
  },
  {
    id: 34,
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    genre: "Fiction",
    price: 15.99,
    language: "English",
    yearPublished: 2018,
    rating: 4.9,
    stockQuantity: 6,
    coverImageUrl: "/example.webp",
    description:
      "A story blending mystery, romance, and nature in the marshlands of North Carolina.",
  },
  {
    id: 35,
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    genre: "Fiction",
    price: 16.99,
    language: "English",
    yearPublished: 2017,
    rating: 4.8,
    stockQuantity: 11,
    coverImageUrl: "/example.webp",
    description:
      "An intriguing novel about the life and loves of a Hollywood icon and the secrets she reveals.",
  },
  {
    id: 36,
    title: "Project Hail Mary",
    author: "Andy Weir",
    genre: "Sci-Fi",
    price: 18.99,
    language: "English",
    yearPublished: 2021,
    rating: 4.9,
    stockQuantity: 5,
    coverImageUrl: "/example.webp",
    description:
      "A thrilling space adventure about a lone astronaut on a mission to save humanity.",
  },
  {
    id: 37,
    title: "Verity",
    author: "Colleen Hoover",
    genre: "Romance",
    price: 13.49,
    language: "English",
    yearPublished: 2018,
    rating: 4.7,
    stockQuantity: 14,
    coverImageUrl: "/example.webp",
    description:
      "A romantic thriller about a writer who uncovers shocking truths while completing a manuscript.",
  },
  {
    id: 38,
    title: "The Paris Library",
    author: "Janet Skeslien Charles",
    genre: "Historical Fiction",
    price: 14.99,
    language: "English",
    yearPublished: 2021,
    rating: 4.6,
    stockQuantity: 10,
    coverImageUrl: "/example.webp",
    description:
      "A novel about the power of books and the bravery of librarians during World War II.",
  },
  {
    id: 39,
    title: "Shantaram",
    author: "Gregory David Roberts",
    genre: "Fiction",
    price: 17.99,
    language: "English",
    yearPublished: 2003,
    rating: 4.7,
    stockQuantity: 9,
    coverImageUrl: "/example.webp",
    description:
      "An epic tale of love, betrayal, and survival in the underworld of Bombay, India.",
  },
  {
    id: 40,
    title: "Cloud Atlas",
    author: "David Mitchell",
    genre: "Fiction",
    price: 15.99,
    language: "English",
    yearPublished: 2004,
    rating: 4.6,
    stockQuantity: 8,
    coverImageUrl: "/example.webp",
    description:
      "A layered narrative connecting characters across centuries in an intricate, thought-provoking story.",
  },
];

export default books;
